version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/homemate-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/homemate-frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
