// Re-export all admin API functions from the dedicated API module
export {
  getUsers,
  getTaskers,
  createUser,
  updateUser,
  suspendUser,
  promoteUser,
  demoteUser,
  reactiveUser,
  createTasker,
  updateTasker,
  suspendTasker,
  reactiveTasker,
  suspendTaskers,
  reactiveTaskers,
  demoteUsers,
  promoteUsers,
  suspendUsers,
  reactiveUsers,
  getReports,
  respondToReport,
  getAnalysis,
  getUserGenderCount,
  getUserStatusCounts,
  getUserAgeBuckets,
  getUserNewAccounts,
  getTaskerGenderCount,
  getTaskerAgeBuckets,
  getTaskerNewAccounts,
  getTaskerRatingRanges,
  getTaskerHourRateRanges,
  getTaskerWorkedHoursRanges,
  getTaskerServiceCounts,
  getTaskerCityCounts,
  getTaskerStatusCounts,
  getTaskStartDateRanges,
  getTaskEndDateRanges,
  getTaskBillRanges,
  getTaskStatusCounts,
  default,
} from '../api/adminApi';


