use HomeMate;

ALTER TABLE Tasker
MODIFY COLUMN hourRate DOUBLE NOT NULL DEFAULT 0;

ALTER TABLE Task
MODIFY COLUMN workedHours DOUBLE NOT NULL DEFAULT 0;

ALTER TABLE Task
MODIFY COLUMN bill DOUBLE NOT NULL DEFAULT 0;
